name: MQL5 Compile

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # It's good practice to use v4 here too

    - name: Compile MQL5 Code
      uses: fx31337/mql-compile-action@v2
      with:
        path: 'AdvancedRiskCalculator.mq5'
        include: '.'
        log-file: 'compile-results.log'
        ignore-warnings: false
        verbose: true

    - name: Upload compiled file and logs
      uses: actions/upload-artifact@v4 # The corrected version
      with:
        name: compiled-expert-advisor
        path: |
          MQL5/Experts/AdvancedRiskCalculator.ex5
          compile-results.log